// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "Lyra",
    platforms: [.macOS(.v13), .iOS(.v16)],
    products: [
        .library(
            name: "Lyra",
            targets: ["Lyra"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/swiftlang/swift-foundation-icu", branch: "main")
    ],
    targets: [
        .target(
            name: "CTagLib",
            path: "Lyra/Sources/CTagLib",
            exclude: [
                "taglib/.git",
                "taglib/.github",
                "taglib/examples",
                "taglib/tests",
                "taglib/cmake",
                "taglib/bindings",
                "taglib/doc",
                "taglib/3rdparty/utfcpp/tests",
                "taglib/3rdparty/utfcpp/samples",
                "taglib/CMakeLists.txt",
                "taglib/ConfigureChecks.cmake",
                "taglib/taglib/mpeg/id3v2/id3v2.4.0-frames.txt",
                "taglib/taglib/mpeg/id3v2/id3v2.4.0-structure.txt",
                "taglib/taglib/toolkit/propertymapping.dox",
                "taglib/taglib/toolkit/tlist.tcc",
            ],
            sources: [
                "taglib/taglib/ape/apefile.cpp",
                "taglib/taglib/ape/apefooter.cpp",
                "taglib/taglib/ape/apeitem.cpp",
                "taglib/taglib/ape/apeproperties.cpp",
                "taglib/taglib/ape/apetag.cpp",
                "taglib/taglib/asf/asfattribute.cpp",
                "taglib/taglib/asf/asffile.cpp",
                "taglib/taglib/asf/asfpicture.cpp",
                "taglib/taglib/asf/asfproperties.cpp",
                "taglib/taglib/asf/asftag.cpp",
                "taglib/taglib/audioproperties.cpp",
                "taglib/taglib/dsdiff/dsdiffdiintag.cpp",
                "taglib/taglib/dsdiff/dsdifffile.cpp",
                "taglib/taglib/dsdiff/dsdiffproperties.cpp",
                "taglib/taglib/dsf/dsffile.cpp",
                "taglib/taglib/dsf/dsfproperties.cpp",
                "taglib/taglib/fileref.cpp",
                "taglib/taglib/flac/flacfile.cpp",
                "taglib/taglib/flac/flacmetadatablock.cpp",
                "taglib/taglib/flac/flacpicture.cpp",
                "taglib/taglib/flac/flacproperties.cpp",
                "taglib/taglib/flac/flacunknownmetadatablock.cpp",
                "taglib/taglib/it/itfile.cpp",
                "taglib/taglib/it/itproperties.cpp",
                "taglib/taglib/matroska/ebml/ebmlbinaryelement.cpp",
                "taglib/taglib/matroska/ebml/ebmlelement.cpp",
                "taglib/taglib/matroska/ebml/ebmlfloatelement.cpp",
                "taglib/taglib/matroska/ebml/ebmlmasterelement.cpp",
                "taglib/taglib/matroska/ebml/ebmlmkattachments.cpp",
                "taglib/taglib/matroska/ebml/ebmlmkchapters.cpp",
                "taglib/taglib/matroska/ebml/ebmlmkcues.cpp",
                "taglib/taglib/matroska/ebml/ebmlmkinfo.cpp",
                "taglib/taglib/matroska/ebml/ebmlmkseekhead.cpp",
                "taglib/taglib/matroska/ebml/ebmlmksegment.cpp",
                "taglib/taglib/matroska/ebml/ebmlmktags.cpp",
                "taglib/taglib/matroska/ebml/ebmlmktracks.cpp",
                "taglib/taglib/matroska/ebml/ebmlstringelement.cpp",
                "taglib/taglib/matroska/ebml/ebmluintelement.cpp",
                "taglib/taglib/matroska/ebml/ebmlutils.cpp",
                "taglib/taglib/matroska/ebml/ebmlvoidelement.cpp",
                "taglib/taglib/matroska/matroskaattachedfile.cpp",
                "taglib/taglib/matroska/matroskaattachments.cpp",
                "taglib/taglib/matroska/matroskachapter.cpp",
                "taglib/taglib/matroska/matroskachapteredition.cpp",
                "taglib/taglib/matroska/matroskachapters.cpp",
                "taglib/taglib/matroska/matroskacues.cpp",
                "taglib/taglib/matroska/matroskaelement.cpp",
                "taglib/taglib/matroska/matroskafile.cpp",
                "taglib/taglib/matroska/matroskaproperties.cpp",
                "taglib/taglib/matroska/matroskaseekhead.cpp",
                "taglib/taglib/matroska/matroskasegment.cpp",
                "taglib/taglib/matroska/matroskasimpletag.cpp",
                "taglib/taglib/matroska/matroskatag.cpp",
                "taglib/taglib/mod/modfile.cpp",
                "taglib/taglib/mod/modfilebase.cpp",
                "taglib/taglib/mod/modproperties.cpp",
                "taglib/taglib/mod/modtag.cpp",
                "taglib/taglib/mp4/mp4atom.cpp",
                "taglib/taglib/mp4/mp4coverart.cpp",
                "taglib/taglib/mp4/mp4file.cpp",
                "taglib/taglib/mp4/mp4item.cpp",
                "taglib/taglib/mp4/mp4itemfactory.cpp",
                "taglib/taglib/mp4/mp4properties.cpp",
                "taglib/taglib/mp4/mp4stem.cpp",
                "taglib/taglib/mp4/mp4tag.cpp",
                "taglib/taglib/mpc/mpcfile.cpp",
                "taglib/taglib/mpc/mpcproperties.cpp",
                "taglib/taglib/mpeg/id3v1/id3v1genres.cpp",
                "taglib/taglib/mpeg/id3v1/id3v1tag.cpp",
                "taglib/taglib/mpeg/id3v2/frames/attachedpictureframe.cpp",
                "taglib/taglib/mpeg/id3v2/frames/chapterframe.cpp",
                "taglib/taglib/mpeg/id3v2/frames/commentsframe.cpp",
                "taglib/taglib/mpeg/id3v2/frames/eventtimingcodesframe.cpp",
                "taglib/taglib/mpeg/id3v2/frames/generalencapsulatedobjectframe.cpp",
                "taglib/taglib/mpeg/id3v2/frames/ownershipframe.cpp",
                "taglib/taglib/mpeg/id3v2/frames/podcastframe.cpp",
                "taglib/taglib/mpeg/id3v2/frames/popularimeterframe.cpp",
                "taglib/taglib/mpeg/id3v2/frames/privateframe.cpp",
                "taglib/taglib/mpeg/id3v2/frames/relativevolumeframe.cpp",
                "taglib/taglib/mpeg/id3v2/frames/synchronizedlyricsframe.cpp",
                "taglib/taglib/mpeg/id3v2/frames/tableofcontentsframe.cpp",
                "taglib/taglib/mpeg/id3v2/frames/textidentificationframe.cpp",
                "taglib/taglib/mpeg/id3v2/frames/uniquefileidentifierframe.cpp",
                "taglib/taglib/mpeg/id3v2/frames/unknownframe.cpp",
                "taglib/taglib/mpeg/id3v2/frames/unsynchronizedlyricsframe.cpp",
                "taglib/taglib/mpeg/id3v2/frames/urllinkframe.cpp",
                "taglib/taglib/mpeg/id3v2/id3v2extendedheader.cpp",
                "taglib/taglib/mpeg/id3v2/id3v2footer.cpp",
                "taglib/taglib/mpeg/id3v2/id3v2frame.cpp",
                "taglib/taglib/mpeg/id3v2/id3v2framefactory.cpp",
                "taglib/taglib/mpeg/id3v2/id3v2header.cpp",
                "taglib/taglib/mpeg/id3v2/id3v2synchdata.cpp",
                "taglib/taglib/mpeg/id3v2/id3v2tag.cpp",
                "taglib/taglib/mpeg/mpegfile.cpp",
                "taglib/taglib/mpeg/mpegheader.cpp",
                "taglib/taglib/mpeg/mpegproperties.cpp",
                "taglib/taglib/mpeg/xingheader.cpp",
                "taglib/taglib/ogg/flac/oggflacfile.cpp",
                "taglib/taglib/ogg/oggfile.cpp",
                "taglib/taglib/ogg/oggpage.cpp",
                "taglib/taglib/ogg/oggpageheader.cpp",
                "taglib/taglib/ogg/opus/opusfile.cpp",
                "taglib/taglib/ogg/opus/opusproperties.cpp",
                "taglib/taglib/ogg/speex/speexfile.cpp",
                "taglib/taglib/ogg/speex/speexproperties.cpp",
                "taglib/taglib/ogg/vorbis/vorbisfile.cpp",
                "taglib/taglib/ogg/vorbis/vorbisproperties.cpp",
                "taglib/taglib/ogg/xiphcomment.cpp",
                "taglib/taglib/riff/aiff/aifffile.cpp",
                "taglib/taglib/riff/aiff/aiffproperties.cpp",
                "taglib/taglib/riff/rifffile.cpp",
                "taglib/taglib/riff/wav/infotag.cpp",
                "taglib/taglib/riff/wav/wavfile.cpp",
                "taglib/taglib/riff/wav/wavproperties.cpp",
                "taglib/taglib/s3m/s3mfile.cpp",
                "taglib/taglib/s3m/s3mproperties.cpp",
                "taglib/taglib/shorten/shortenfile.cpp",
                "taglib/taglib/shorten/shortenproperties.cpp",
                "taglib/taglib/shorten/shortentag.cpp",
                "taglib/taglib/tag.cpp",
                "taglib/taglib/tagunion.cpp",
                "taglib/taglib/tagutils.cpp",
                "taglib/taglib/toolkit/tbytevector.cpp",
                "taglib/taglib/toolkit/tbytevectorlist.cpp",
                "taglib/taglib/toolkit/tbytevectorstream.cpp",
                "taglib/taglib/toolkit/tdebug.cpp",
                "taglib/taglib/toolkit/tdebuglistener.cpp",
                "taglib/taglib/toolkit/tfile.cpp",
                "taglib/taglib/toolkit/tfilestream.cpp",
                "taglib/taglib/toolkit/tiostream.cpp",
                "taglib/taglib/toolkit/tpicturetype.cpp",
                "taglib/taglib/toolkit/tpropertymap.cpp",
                "taglib/taglib/toolkit/tstring.cpp",
                "taglib/taglib/toolkit/tstringlist.cpp",
                "taglib/taglib/toolkit/tvariant.cpp",
                "taglib/taglib/toolkit/tversionnumber.cpp",
                "taglib/taglib/toolkit/tzlib.cpp",
                "taglib/taglib/trueaudio/trueaudiofile.cpp",
                "taglib/taglib/trueaudio/trueaudioproperties.cpp",
                "taglib/taglib/wavpack/wavpackfile.cpp",
                "taglib/taglib/wavpack/wavpackproperties.cpp",
                "taglib/taglib/xm/xmfile.cpp",
                "taglib/taglib/xm/xmproperties.cpp",
            ],
            publicHeadersPath: "include",
            cxxSettings: [
                .define("TAGLIB_STATIC"),
                .define("NDEBUG", .when(configuration: .release)),
                .define("HAVE_ZLIB", to: "1"),
                .headerSearchPath("taglib/taglib"),
                .headerSearchPath("taglib/taglib/toolkit"),
                .headerSearchPath("taglib/taglib/mpeg"),
                .headerSearchPath("taglib/taglib/mpeg/id3v1"),
                .headerSearchPath("taglib/taglib/mpeg/id3v2"),
                .headerSearchPath("taglib/taglib/mpeg/id3v2/frames"),
                .headerSearchPath("taglib/taglib/ape"),
                .headerSearchPath("taglib/taglib/mpc"),
                .headerSearchPath("taglib/taglib/wavpack"),
                .headerSearchPath("taglib/taglib/asf"),
                .headerSearchPath("taglib/taglib/dsf"),
                .headerSearchPath("taglib/taglib/dsdiff"),
                .headerSearchPath("taglib/taglib/matroska"),
                .headerSearchPath("taglib/taglib/matroska/ebml"),
                .headerSearchPath("taglib/taglib/it"),
                .headerSearchPath("taglib/taglib/mod"),
                .headerSearchPath("taglib/taglib/s3m"),
                .headerSearchPath("taglib/taglib/xm"),
                .headerSearchPath("taglib/taglib/mp4"),
                .headerSearchPath("taglib/taglib/riff"),
                .headerSearchPath("taglib/taglib/riff/wav"),
                .headerSearchPath("taglib/taglib/riff/aiff"),
                .headerSearchPath("taglib/taglib/shorten"),
                .headerSearchPath("taglib/taglib/trueaudio"),
                .headerSearchPath("taglib/taglib/flac"),
                .headerSearchPath("taglib/taglib/ogg"),
                .headerSearchPath("taglib/taglib/ogg/vorbis"),
                .headerSearchPath("taglib/taglib/ogg/flac"),
                .headerSearchPath("taglib/taglib/ogg/opus"),
                .headerSearchPath("taglib/taglib/ogg/speex"),
                .headerSearchPath("taglib/3rdparty/utfcpp/source"),
            ],
            linkerSettings: [
                .linkedLibrary("z"),
            ]
        ),
        
        .target(
            name: "LyraBridge",
            dependencies: [
                "CTagLib",
                .product(name: "_FoundationICU", package: "swift-foundation-icu")
            ],
            path: "Lyra/Sources/LyraBridge",
            publicHeadersPath: "include",
            cxxSettings: [
                .headerSearchPath("../CTagLib/taglib/taglib"),
                .headerSearchPath("../CTagLib/taglib/taglib/toolkit")
            ],
            linkerSettings: [
                .linkedFramework("AVFoundation"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("AudioToolbox")
            ]
        ),
        
        .target(
            name: "Lyra",
            dependencies: ["LyraBridge"],
            path: "Lyra/Sources/Lyra",
            swiftSettings: [
                .interoperabilityMode(.Cxx)
            ]
        ),
        
        .testTarget(
            name: "LyraTests",
            dependencies: ["Lyra"],
            path: "Lyra/Tests",
            resources: [
                .copy("TestAudio")
            ],
            swiftSettings: [
                .interoperabilityMode(.Cxx)
            ]
        ),
    ],
    cxxLanguageStandard: .cxx17
)
